kind: ServiceAccount
apiVersion: v1
metadata:
  name: backstage
  namespace: backstage
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage
subjects:
  - kind: ServiceAccount
    name: backstage
    namespace: backstage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: backstage-svc
  annotations:
    kubernetes.io/service-account.name: backstage