kind: ServiceAccount
apiVersion: v1
metadata:
  name: backstage
  namespace: backstage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: backstage-svc
  annotations:
    kubernetes.io/service-account.name: backstage